application: bustracker-app
version: 2
runtime: php55
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /(.+\.php)$
  script: \1

- url: /.*
  script: index.php